insert into ttkd_bsc.ct_bsc_ptm(dich_vu, dichvuvt_id, loaitb_id, tenkieu_ld, kieuld_id, loaihd_id
			,THANG_TLKPI_HOTRO,THANG_TLDG_DT_NVHOTRO,THANG_TLKPI_DNHM,THANG_TLDG_DNHM,THANG_PTM,NGUON,GHI_CHU
			,MA_TB,GOI_CUOC,sothang_dc,MANV_PTM,TENNV_PTM,ma_to,ten_to,ma_pb,ten_pb,TIEN_DNHM,DOANHTHU_DONGIA_DNHM,LUONG_DONGIA_DNHM_NVPTM,MANV_hotro,
            mato_hotro,mapb_hotro,dthu_goi,datcoc_csd,DOANHTHU_DONGIA_NVHOTRO,LUONG_DONGIA_NVHOTRO,DOANHTHU_KPI_DNHM,DOANHTHU_KPI_NVHOTRO,LYDO_KHONGTINH_DONGIA)
		  
select 'VNPTT', 2, 21, 'Hòa mạng mới di động' tenkieu_ld, 2 kieuld_id, 1 loaihd_id,THANG_PTM,THANG_PTM,THANG_PTM,THANG_PTM,THANG_PTM
			,NGUON,PHAN_LOAI_KENH,MA_TB,TEN_GOI,CK_GOI_TLDG,MANV_PTM,TENNV_PTM,MATO_PTM,TENTO_PTM,MAPB_PTM,TENPB_PTM,TIEN_DNHM,DTHU_DONGIA_DNHM
            ,TIEN_THULAO_DNHM,MANV_GOI,MATO_GOI,MAPB_GOI,TIEN_GOI,TIEN_GOI,DTHU_DONGIA_GOI,TIEN_THULAO_GOI
		  ,DTHU_DNHM_KPI,DTHU_KPI,(LYDO_KHONGTINH|| ';'||LYDO_KHONGTINH_KPI) LYDO_KHONGTINH_DONGIA
		  from vietanhvh.one_line_202409
		  where thang_ptm = 202409
            ;
